version: "2.15.1"

services:
  server:
    image: myserver
    ports: 
      - "127.0.0.1:8000:8000"
    networks: 
      serverConnection:
        ipv4_address: 192.168.77.77
  client:
    image: testclient
    networks:
      serverConnection:
        ipv4_address: 192.168.77.90
    depends_on: 
      - server
    restart: on-failure
networks:
  serverConnection:
    ipam:
      driver: default
      config:
        - subnet: 192.168.77.0/24